export type Language = "zh" | "en";

export const copy = {
  zh: {
    navProblems: "题库",
    navTasks: "任务模式",
    navReviews: "审核模式",
    navRubrics: "Rubrics",
    navDiscuss: "讨论",
    login: "GitHub 登录",
    noticeStrong: "AgentCode V0",
    notice: "当前上线 20 道高质量 Review Mode 题，先训练 AI PR 审核判断力。",
    eyebrow: "ENGINEERING PRACTICE / REVIEW MODE",
    headline: "真实工程题库：审核 AI 写出的 PR",
    lede:
      "AgentCode 保留熟悉的题库体验，但训练内容换成真实工程判断。当前 20 道题都来自真实开源问题、安全公告或 SWE-bench 案例，你需要读 diff、看测试、找风险，并判断 AI PR 能不能合并。",
    startTask: "开始 Review 001",
    viewRoadmap: "查看 V0 计划",
    seedChallenges: "SEED CHALLENGES",
    taskMode: "TASK MODE PLANNED",
    reviewMode: "REVIEW MODE READY",
    search: "搜索题目、标签、PR 风险...",
    filterAll: "全部模式",
    filterDifficulty: "难度",
    filterStatus: "状态",
    challengeList: "练习题库",
    seeAll: "查看全部",
    tableTitle: "题目",
    tableMode: "模式",
    tableDifficulty: "难度",
    tableAcceptance: "通过率",
    tableStatus: "状态",
    planTitle: "今日训练计划",
    planBody: "先做 1 道安全题，再做 1 道框架或数据语义题。目标不是刷数量，而是看你能否判断一个 AI PR 是否能合并。",
    reviewPreview: "Review 预览",
    practice: "练习",
    reviewBadge: "PR 审核题",
    rubricTitle: "评估 Rubric",
    correctness: "正确性",
    testQuality: "测试质量",
    riskJudgment: "风险判断",
    maintainability: "可维护性",
    task: "Task",
    review: "Review",
    junior: "Junior",
    mid: "Mid",
    senior: "Senior",
    ready: "Ready",
    draft: "Draft",
    needsReview: "需审核"
  },
  en: {
    navProblems: "Problems",
    navTasks: "Task Mode",
    navReviews: "Review Mode",
    navRubrics: "Rubrics",
    navDiscuss: "Discuss",
    login: "GitHub Login",
    noticeStrong: "AgentCode V0",
    notice: "20 high-quality Review Mode challenges are live for AI PR review practice.",
    eyebrow: "ENGINEERING PRACTICE / REVIEW MODE",
    headline: "A real engineering problem set for reviewing AI PRs.",
    lede:
      "AgentCode keeps the familiar problem-set experience, but changes what you practice: read diffs, inspect tests, find regressions, and decide whether AI-generated PRs can be merged. The current set includes 20 traceable review challenges.",
    startTask: "Start Review 001",
    viewRoadmap: "View V0 plan",
    seedChallenges: "SEED CHALLENGES",
    taskMode: "TASK MODE PLANNED",
    reviewMode: "REVIEW MODE READY",
    search: "Search challenges, tags, PR risks...",
    filterAll: "All modes",
    filterDifficulty: "Difficulty",
    filterStatus: "Status",
    challengeList: "Practice Problems",
    seeAll: "See all",
    tableTitle: "Title",
    tableMode: "Mode",
    tableDifficulty: "Difficulty",
    tableAcceptance: "Acceptance",
    tableStatus: "Status",
    planTitle: "Today's Practice Plan",
    planBody: "Start with 1 security review and 1 framework or data-semantics review. The goal is judgment, not volume.",
    reviewPreview: "Review Preview",
    practice: "Practice",
    reviewBadge: "PR Review",
    rubricTitle: "Evaluation Rubric",
    correctness: "Correctness",
    testQuality: "Test quality",
    riskJudgment: "Risk judgment",
    maintainability: "Maintainability",
    task: "Task",
    review: "Review",
    junior: "Junior",
    mid: "Mid",
    senior: "Senior",
    ready: "Ready",
    draft: "Draft",
    needsReview: "Review"
  }
} as const;
