export type Language = "zh" | "en";

export const copy = {
  zh: {
    navProblems: "题库",
    navTasks: "任务模式",
    navReviews: "审核模式",
    navRubrics: "Rubrics",
    navDiscuss: "讨论",
    login: "GitHub 登录",
    noticeStrong: "AgentCode V0",
    notice: "先做 20 道高质量工程题，训练真实交付和代码审核能力。",
    eyebrow: "ENGINEERING PRACTICE / TASK + REVIEW",
    headline: "真实工程题库：交付任务与审核 PR",
    lede:
      "AgentCode 保留熟悉的题库体验，但训练内容换成真实工程任务和 PR 审核。你需要完成改动、补测试、读 diff、看 runner 结果，并判断代码能不能合并。",
    startTask: "开始第一题",
    viewRoadmap: "查看 V0 计划",
    seedChallenges: "SEED CHALLENGES",
    taskMode: "TASK MODE",
    reviewMode: "REVIEW MODE",
    search: "搜索题目、标签、PR 风险...",
    filterAll: "全部模式",
    filterDifficulty: "难度",
    filterStatus: "状态",
    challengeList: "练习题库",
    seeAll: "查看全部",
    tableTitle: "题目",
    tableMode: "模式",
    tableDifficulty: "难度",
    tableAcceptance: "通过率",
    tableStatus: "状态",
    planTitle: "今日训练计划",
    planBody: "先完成 1 道 Task，再做 1 道 Review。目标不是刷数量，而是看你能否交付和判断。",
    reviewPreview: "Review 预览",
    practice: "练习",
    reviewBadge: "PR 审核题",
    rubricTitle: "评估 Rubric",
    correctness: "正确性",
    testQuality: "测试质量",
    riskJudgment: "风险判断",
    maintainability: "可维护性",
    task: "Task",
    review: "Review",
    junior: "Junior",
    mid: "Mid",
    senior: "Senior",
    ready: "Ready",
    draft: "Draft",
    needsReview: "需审核"
  },
  en: {
    navProblems: "Problems",
    navTasks: "Task Mode",
    navReviews: "Review Mode",
    navRubrics: "Rubrics",
    navDiscuss: "Discuss",
    login: "GitHub Login",
    noticeStrong: "AgentCode V0",
    notice: "Start with 20 high-quality engineering challenges for delivery and code review skills.",
    eyebrow: "ENGINEERING PRACTICE / TASK + REVIEW",
    headline: "A real engineering problem set: ship tasks and review PRs.",
    lede:
      "AgentCode keeps the familiar problem-set experience, but changes what you practice: complete implementation tasks, add tests, read diffs, inspect runner results, and decide whether code can be merged.",
    startTask: "Start first challenge",
    viewRoadmap: "View V0 plan",
    seedChallenges: "SEED CHALLENGES",
    taskMode: "TASK MODE",
    reviewMode: "REVIEW MODE",
    search: "Search challenges, tags, PR risks...",
    filterAll: "All modes",
    filterDifficulty: "Difficulty",
    filterStatus: "Status",
    challengeList: "Practice Problems",
    seeAll: "See all",
    tableTitle: "Title",
    tableMode: "Mode",
    tableDifficulty: "Difficulty",
    tableAcceptance: "Acceptance",
    tableStatus: "Status",
    planTitle: "Today's Practice Plan",
    planBody: "Complete 1 Task and 1 Review. The goal is not volume; it is delivery and judgment.",
    reviewPreview: "Review Preview",
    practice: "Practice",
    reviewBadge: "PR Review",
    rubricTitle: "Evaluation Rubric",
    correctness: "Correctness",
    testQuality: "Test quality",
    riskJudgment: "Risk judgment",
    maintainability: "Maintainability",
    task: "Task",
    review: "Review",
    junior: "Junior",
    mid: "Mid",
    senior: "Senior",
    ready: "Ready",
    draft: "Draft",
    needsReview: "Review"
  }
} as const;
