import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  challengeDirectories,
  formatOrderList,
  readJson,
  repoRoot
} from "./lib.mjs";

function groupsText(groups = []) {
  return groups.map((group) => group.join(" + ")).join(" OR ") || "-";
}

function rubricMarkdown(metadata, expected) {
  const sections = [...expected.requiredFindings, ...(expected.optionalFindings ?? [])].map((finding) => [
    `## ${finding.id}`,
    "",
    `- Kind: ${finding.kind}`,
    `- Required: ${finding.required}`,
    `- Severity: ${finding.severity}`,
    `- Blocks merge: ${finding.blocksMerge}`,
    `- Summary: ${finding.summary}`,
    `- Anchors: ${finding.anchors.map((anchor) => `${anchor.fileName}:${anchor.startLine}-${anchor.endLine}`).join(", ")}`,
    `- Problem: ${groupsText(finding.criteria?.problem)}`,
    `- Evidence: ${groupsText(finding.criteria?.evidence)}`,
    `- Impact: ${groupsText(finding.criteria?.impact)}`,
    `- Fix: ${groupsText(finding.criteria?.fix)}`,
    `- Tests: ${groupsText(finding.criteria?.tests)}`,
    ""
  ].join("\n"));

  return [
    `# ${metadata.id} rubric (generated)`,
    "",
    "> Generated from expected-findings.json. Do not edit this file by hand.",
    "",
    `- Merge: ${expected.canMerge ? "approve" : "request changes"}`,
    `- Schema: ${expected.schemaVersion}`,
    "",
    ...sections
  ].join("\n");
}

function fixtureFrom(metadata, expected, locale) {
  const requiredCore = expected.requiredFindings.filter((finding) => finding.kind !== "test");
  const requiredTests = expected.requiredFindings.filter((finding) => finding.kind === "test");
  const findings = requiredCore.map((finding, index) => ({
    id: `${locale}-${index + 1}`,
    fileName: finding.anchors[0].fileName,
    lineNumber: finding.anchors[0].startLine,
    severity: finding.severity,
    blocksMerge: finding.blocksMerge,
    problem: [finding.summary, ...(finding.criteria.problem ?? []).flat()].join(" "),
    evidence: [finding.expectedReasoning ?? "", ...(finding.criteria.evidence ?? []).flat()].join(" "),
    impact: [finding.expectedReasoning ?? "", ...(finding.criteria.impact ?? []).flat()].join(" "),
    fix: [finding.acceptableFix ?? "", ...(finding.criteria.fix ?? []).flat()].join(" ")
  }));
  const tests = requiredTests.map((finding) => [
    finding.summary,
    finding.expectedReasoning ?? "",
    ...(finding.criteria.tests ?? []).flat()
  ].join(" ")).join("\n") || `Test analysis: ${(metadata.scoringHints?.testTerms ?? []).join(" ")}`;
  return {
    mergeDecision: expected.canMerge ? "yes" : "no",
    conclusion: locale === "zh"
      ? expected.canMerge ? "评审结论：逐项核验完成，可以合并。" : "评审结论：存在阻塞问题，请求修改。"
      : expected.canMerge ? "Review decision: approve after completing the checks below." : "Review decision: request changes for the blocking finding below.",
    findings,
    tests
  };
}

function fixtureSet(metadata, expected) {
  const strongZh = fixtureFrom(metadata, expected, "zh");
  const strongEn = fixtureFrom(metadata, expected, "en");
  const first = strongEn.findings[0];
  const partialFindings = strongEn.findings.length >= 3 ? strongEn.findings.slice(0, 2) : first ? [first] : [];
  const firstPhysicalFile = Object.values(expected.requiredFindings)
    .flatMap((finding) => finding.anchors ?? [])
    .at(0);
  const disallowed = expected.disallowedConclusions?.[0];
  const disallowedText = typeof disallowed === "string" ? disallowed : disallowed?.description ?? "unsupported conclusion";

  return {
    "strong-zh.json": { expected: { minScore: 100, maxScore: 100 }, draft: strongZh },
    "strong-en.json": { expected: { minScore: 100, maxScore: 100 }, draft: strongEn },
    "partial.json": {
      expected: { minScore: 40, maxScore: 79 },
      draft: {
        mergeDecision: expected.canMerge ? "yes" : "no",
        conclusion: "I found the main concern but have not completed the evidence, impact, fix, or test analysis.",
        findings: partialFindings.map((finding) => ({ ...finding, evidence: "", impact: "", fix: "" })),
        tests: ""
      }
    },
    "wrong-disallowed.json": {
      expected: { minScore: 0, maxScore: 30 },
      draft: {
        mergeDecision: expected.canMerge ? "no" : "yes",
        conclusion: disallowedText,
        findings: [],
        tests: ""
      }
    },
    "keyword-stuffing-fabricated-location.json": {
      expected: { validationError: true, maxScore: 60 },
      draft: {
        mergeDecision: expected.canMerge ? "yes" : "no",
        conclusion: "Keyword-only answer with a fabricated location.",
        findings: first ? [{
          ...first,
          id: "keyword-stuffing",
          fileName: firstPhysicalFile?.fileName ?? "missing.diff",
          lineNumber: 999999,
          problem: expected.requiredFindings.flatMap((finding) => Object.values(finding.criteria ?? {}).flat(2)).join(" "),
          evidence: expected.requiredFindings.flatMap((finding) => Object.values(finding.criteria ?? {}).flat(2)).join(" "),
          impact: expected.requiredFindings.flatMap((finding) => Object.values(finding.criteria ?? {}).flat(2)).join(" "),
          fix: expected.requiredFindings.flatMap((finding) => Object.values(finding.criteria ?? {}).flat(2)).join(" ")
        }] : [],
        tests: expected.requiredFindings.flatMap((finding) => Object.values(finding.criteria ?? {}).flat(2)).join(" ")
      }
    }
  };
}

const rows = [];
for (const { dir } of challengeDirectories()) {
  const metadata = readJson(join(dir, "metadata.json"));
  const expected = readJson(join(dir, "expected-findings.json"));
  writeFileSync(join(dir, "rubric.md"), `${rubricMarkdown(metadata, expected).trimEnd()}\n`);

  const fixtureDir = join(dir, "fixtures");
  mkdirSync(fixtureDir, { recursive: true });
  for (const [name, fixture] of Object.entries(fixtureSet(metadata, expected))) {
    writeFileSync(join(fixtureDir, name), `${JSON.stringify(fixture, null, 2)}\n`);
  }
  rows.push({ order: metadata.order, canMerge: expected.canMerge });
}

const matrixPath = join(repoRoot, "docs", "zh", "challenge-matrix.md");
let matrix = readFileSync(matrixPath, "utf8");
const reject = rows.filter((row) => !row.canMerge).map((row) => row.order);
const approve = rows.filter((row) => row.canMerge).map((row) => row.order);
matrix = matrix
  .replace(
    /\| 不能合并（trap，貌似合理但有阻塞问题） \|.*\| \d+ \|/,
    `| 不能合并（trap，貌似合理但有阻塞问题） | ${formatOrderList(reject)} | ${reject.length} |`
  )
  .replace(
    /\| 可以合并（改编自上游正确修复，正确结论是 approve） \|.*\| \d+ \|/,
    `| 可以合并（改编自上游正确修复，正确结论是 approve） | ${formatOrderList(approve)} | ${approve.length} |`
  );
writeFileSync(matrixPath, matrix);

process.stdout.write(`generated rubrics and ${rows.length * 5} fixtures; matrix=${reject.length}/${approve.length}\n`);
